
mkdir -p ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/intel-openmp-2020.2-254.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/_libgcc_mutex-0.1-conda_forge.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/_tflow_select-2.3.0-mkl.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ca-certificates-2020.6.20-hecda079_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/font-ttf-inconsolata-2.001-hab24e00_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/font-ttf-source-code-pro-2.030-hab24e00_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/font-ttf-ubuntu-0.83-hab24e00_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ld_impl_linux-64-2.35-h769bd43_9.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libgfortran4-7.5.0-hae1eefd_17.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libstdcxx-ng-9.3.0-h2ae2ef3_17.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/llvm-openmp-10.0.1-hc9558a2_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/mysql-common-8.0.21-2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pandoc-2.10.1-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/_openmp_mutex-4.5-1_llvm.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fonts-conda-forge-1-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libgfortran-ng-7.5.0-hae1eefd_17.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fonts-conda-ecosystem-1-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libgcc-ng-9.3.0-h5dbcf3e_17.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/mkl-2020.2-256.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/abseil-cpp-20200225.2-he1b5a44_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/aws-c-common-0.4.59-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/blosc-1.20.1-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/brotli-1.0.9-he1b5a44_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/bzip2-1.0.8-h516909a_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/c-ares-1.16.1-h516909a_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/charls-2.1.0-he1b5a44_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cudatoolkit-10.2.89-hfd86e86_1.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/expat-2.2.9-he1b5a44_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fribidi-1.0.10-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/geos-3.8.1-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gflags-2.2.2-he1b5a44_1004.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/giflib-5.2.1-h516909a_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gmp-6.2.0-he1b5a44_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/graphite2-1.3.13-he1b5a44_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/icu-67.1-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jpeg-9d-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jxrlib-1.1-h516909a_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/lame-3.100-h14c3975_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/lerc-2.2-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libaec-1.0.4-he1b5a44_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libblas-3.8.0-16_mkl.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libev-4.33-h516909a_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libffi-3.2.1-he1b5a44_1007.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libiconv-1.16-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libsodium-1.0.18-h516909a_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libtool-2.4.6-h516909a_1005.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libutf8proc-2.5.0-h516909a_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libuuid-2.32.1-h14c3975_1000.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libwebp-base-1.1.0-h516909a_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libxkbcommon-0.10.0-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libzopfli-1.0.3-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/lz4-c-1.9.2-he1b5a44_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ncurses-6.2-he1b5a44_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nettle-3.4.1-h1bed415_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ninja-1.10.1-hc9558a2_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nspr-4.29-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/openssl-1.1.1h-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pcre-8.44-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/perl-5.30.3-h516909a_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pixman-0.38.0-h516909a_1003.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pthread-stubs-0.4-h14c3975_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/re2-2020.10.01-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/snappy-1.1.8-he1b5a44_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libice-1.0.10-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxau-1.0.9-h14c3975_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xxhash-0.8.0-h516909a_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xz-5.2.5-h516909a_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/yaml-0.2.5-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/zfp-0.5.5-he1b5a44_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/zlib-1.2.11-h516909a_1009.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/aws-checksums-0.1.9-he252421_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/brunsli-0.1-he1b5a44_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gettext-0.19.8.1-hc5be6a0_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/glog-0.4.0-h49b9bf7_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gnutls-3.6.13-h79a8f9a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gperftools-2.7-h767d802_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/hdf5-1.10.6-nompi_h3c11f04_101.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jasper-1.900.1-h07fcdf6_1006.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libcblas-3.8.0-16_mkl.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libedit-3.1.20191231-he28a2e2_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libevent-2.1.10-hcdb4288_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/liblapack-3.8.0-16_mkl.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libllvm10-10.0.1-he513fc3_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libnghttp2-1.41.0-h8cfc5f6_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libpng-1.6.37-hed695b0_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libprotobuf-3.13.0-h8b12597_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libssh2-1.9.0-hab1572f_5.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libxcb-1.13-h14c3975_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libxml2-2.9.10-h68273f3_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/openh264-2.1.1-h8b12597_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/readline-8.0-he28a2e2_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tk-8.6.10-hed695b0_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/zeromq-4.3.3-he1b5a44_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/zstd-1.4.5-h6597ccf_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/aws-c-event-stream-0.1.6-h84e28f3_5.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/freetype-2.10.2-he06d7ca_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/grpc-cpp-1.32.0-h7997a97_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/krb5-1.17.1-hfafb76e_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libclang-10.0.1-default_hde54327_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/liblapacke-3.8.0-16_mkl.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libthrift-0.13.0-h5aa387f_6.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libtiff-4.1.0-hc7e4089_6.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/mysql-libs-8.0.21-hf3661c5_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/orc-1.6.5-hd3605a7_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/sqlite-3.33.0-h4cf870e_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libx11-1.6.12-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/blas-2.16-mkl.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ffmpeg-4.3-hf484d3e_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fontconfig-2.13.1-h1056068_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/lcms2-2.11-hbd6801e_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libcurl-7.71.1-hcdd3856_8.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libpq-12.3-h5513abc_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libwebp-1.1.0-h56121f0_4.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nss-3.57-he751ad9_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/openjpeg-2.3.1-h981e76c_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/python-3.8.5-h1103e12_9_cpython.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxext-1.3.4-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxt-1.1.5-h516909a_1003.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/appdirs-1.4.3-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/astor-0.8.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/async-timeout-3.0.1-py_1000.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/async_generator-1.10-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/attrs-20.2.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/aws-sdk-cpp-1.8.59-h9b98462_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/backcall-0.2.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/backports-1.0-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/blinker-1.4-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cachetools-4.1.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/catalogue-1.0.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/click-7.1.2-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cloudpickle-1.6.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/colorama-0.4.3-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/decorator-4.4.2-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/defusedxml-0.6.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/dill-0.3.2-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/distlib-0.3.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/filelock-3.0.12-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/funcsigs-1.0.2-py_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gast-0.3.3-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/glib-2.66.1-h680cd38_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/idna-2.10-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ipython_genutils-0.2.0-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jmespath-0.10.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/json5-0.9.5-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nest-asyncio-1.4.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/olefile-0.46-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pandocfilters-1.4.2-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/parso-0.7.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/plac-0.9.6-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/prometheus_client-0.8.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ptyprocess-0.6.0-py_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyasn1-0.4.8-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pycparser-2.20-pyh9f0ad1d_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyparsing-2.4.7-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/python_abi-3.8-1_cp38.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pytz-2020.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/qtpy-1.9.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/send2trash-1.5.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/six-1.15.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tabulate-0.8.7-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tensorboard-plugin-wit-1.6.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/termcolor-1.1.0-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/testpath-0.4.4-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/threadpoolctl-2.1.0-pyh5ca1d4c_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/toolz-0.11.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tqdm-4.50.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/typing_extensions-3.7.4.2-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/wasabi-0.8.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/webencodings-0.5.1-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/werkzeug-1.0.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/xorg-libxpm-3.5.13-h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/zipp-3.3.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/absl-py-0.10.0-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/astunparse-1.6.3-py_0.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cairo-1.16.0-h3fc0475_1005.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/certifi-2020.6.20-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cffi-1.14.3-py38h5bae8af_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/chardet-3.0.4-py38h32f6830_1007.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cycler-0.10.0-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cymem-2.0.3-py38h950e882_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cytoolz-0.11.0-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/dbus-1.13.6-he372182_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/entrypoints-0.3-py38h32f6830_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/future-0.18.2-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/google-pasta-0.2.0-pyh8c360ce_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gstreamer-1.14.5-h36ae1b5_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gts-0.7.6-h08bb679_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/humanfriendly-8.2-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/importlib-metadata-2.0.0-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jedi-0.17.2-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/kiwisolver-1.2.0-py38hbf85e49_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/markupsafe-1.1.1-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/mistune-0.8.4-py38h1e0a361_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/mkl-service-2.3.0-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/multidict-4.7.5-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/multiprocess-0.70.10-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/murmurhash-1.0.0-py38h950e882_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/numpy-1.19.1-py38hbc27379_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/orderedmultidict-1.0.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/packaging-20.4-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pathlib2-2.3.5-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pexpect-4.8.0-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pickleshare-0.7.5-py38h32f6830_1001.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pillow-7.2.0-py38h9776b28_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/portalocker-1.7.0-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/psutil-5.7.2-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyasn1-modules-0.2.7-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyhocon-0.3.54-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyrsistent-0.17.3-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pysocks-1.7.1-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/python-dateutil-2.8.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyyaml-5.3.1-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyzmq-19.0.2-py38ha71036d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/regex-2020.9.27-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/retrying-1.3.3-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/rsa-4.6-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/sentencepiece-0.1.91-py38hbf85e49_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/srsly-1.0.2-py38h950e882_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tokenizers-0.8.1-py38h2cef62f_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tornado-6.0.4-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/traitlets-5.0.4-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/typing-3.7.4.3-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/typing-extensions-3.7.4.2-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/virtualenv-20.0.20-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/wrapt-1.12.1-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/argon2-cffi-20.1.0-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/arrow-cpp-1.0.1-py38h39ad894_12_cpu.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/brotlipy-0.7.0-py38h1e0a361_1000.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cryptography-3.1.1-py38h766eaa4_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/cython-blis-0.4.1-py38h1e0a361_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/dask-core-2.29.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/furl-2.1.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gobject-introspection-1.66.1-py38h03d966d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gst-plugins-base-1.14.5-h0935bb2_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/h5py-2.10.0-nompi_py38hfb01d0b_104.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/harfbuzz-2.7.2-hee91db6_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/imagecodecs-2020.5.30-py38h36e1e94_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/imageio-2.9.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/importlib_metadata-2.0.0-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyter_core-4.6.3-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/markdown-3.2.2-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/opt_einsum-3.3.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pandas-1.1.2-py38h950e882_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/preshed-3.0.2-py38h950e882_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pytorch-1.6.0-py3.8_cuda10.2.89_cudnn7.6.5_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pywavelets-1.1.1-py38hab2c0dc_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/scipy-1.5.2-py38h8c5af15_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/setuptools-49.6.0-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/shapely-1.7.1-py38hc7361b7_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/terminado-0.9.1-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/yacs-0.1.6-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/yarl-1.4.2-py38h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/aiohttp-3.6.2-py38h516909a_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/atk-1.0-2.36.0-h516909a_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/backports.functools_lru_cache-1.6.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/bleach-3.2.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fvcore-0.1.2.post20200929-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gdk-pixbuf-2.38.2-h3f25603_4.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/grpcio-1.31.0-py38h2c89da0_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jinja2-2.11.2-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/joblib-0.17.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jsonschema-3.2.0-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyter_client-6.1.7-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/keras-preprocessing-1.1.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/matplotlib-base-3.3.2-py38h91b0d89_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/networkx-2.5-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pango-1.42.4-h7062337_4.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/parquet-cpp-1.5.1-2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/patsy-0.5.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pip-20.2.3-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/plotly-4.11.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/protobuf-3.13.0-py38h950e882_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pygments-2.7.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyjwt-1.7.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyopenssl-19.1.0-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/qt-5.12.9-h1f2b2cb_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/thinc-7.4.1-py38hbf85e49_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tifffile-2020.10.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/torchaudio-0.6.0-py38.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/torchvision-0.7.0-py38_cu102.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/atk-2.36.0-2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fastcore-1.0.19-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fastprogress-1.0.0-pyh39e3cac_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fastscript-1.0.0-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/google-auth-1.22.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyterlab_pygments-0.1.2-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/libopencv-4.4.0-py38_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/matplotlib-3.3.2-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nb_conda_kernels-2.3.0-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nbformat-5.0.7-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/oauthlib-3.0.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/onnx-1.7.0-py38h8b45335_4.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyarrow-1.0.1-py38h9235441_12_cpu.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pyqt-5.12.3-py38ha8c2ead_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/sacremoses-0.0.43-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/scikit-image-0.17.2-py38hc5bc63f_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/scikit-learn-0.23.2-py38hee58b96_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/seaborn-base-0.11.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/statsmodels-0.12.0-py38h1e0a361_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tensorflow-base-2.2.0-mkl_py38h5059a2d_0.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tensorflow-estimator-2.2.0-pyh95af2a2_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/urllib3-1.25.10-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/wcwidth-0.2.5-pyh9f0ad1d_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/botocore-1.18.11-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/captum-0.2.0-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/gtk2-2.24.32-h194ddfc_3.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nbclient-0.5.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/prompt-toolkit-3.0.7-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/py-opencv-4.4.0-py38h23f93f0_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/requests-2.24.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/seaborn-0.11.0-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/graphviz-2.42.3-h6939c30_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ipython-7.18.1-py38h1cdfbd6_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nbconvert-6.0.7-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/opencv-4.4.0-py38_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/prompt_toolkit-3.0.7-0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/requests-file-1.5.1-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/requests-oauthlib-1.3.0-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/s3transfer-0.3.3-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/spacy-2.3.2-py38hbf85e49_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/torchtext-0.7.0-py38.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/boto3-1.15.11-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/fastai-2.0.15-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/google-auth-oauthlib-0.4.1-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/imgaug-0.4.0-py_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ipykernel-5.3.4-py38h23f93f0_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nbdev-0.2.40-pyh39e3cac_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pydot-1.4.1-py38h32f6830_1002.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/albumentations-0.4.6-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyter_console-6.2.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/notebook-6.1.4-py38h32f6830_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/qtconsole-4.7.7-pyh9f0ad1d_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tensorboard-2.3.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyterlab_server-1.2.0-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/nb_conda-2.2.1-py38_2.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/pytorch-lightning-0.8.5-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/tensorflow-2.2.0-mkl_py38h6d3daf0_0.conda ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/widgetsnbextension-3.5.1-py38h32f6830_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/ipywidgets-7.5.1-pyh9f0ad1d_1.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyterlab-2.2.8-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/transformers-3.3.1-py_0.tar.bz2 ~/docker/ml-training/files/pkgs
cp ~/programming/python/miniconda3/pkgs/jupyter-1.0.0-py_2.tar.bz2 ~/docker/ml-training/files/pkgs
